In [3]:
# Numpy Array Iteration
import numpy as np
arr = np.ones(10, dtype='int')
for a in arr:
    print(a, end=" ")

1 1 1 1 1 1 1 1 1 1 

In [6]:
twodarr = np.array([[1,2,3,4,5],[6,7,8,9,0]])
for a in twodarr:
    print(a, end=" ")
print()
for a in twodarr:
    for b in a:
        print(b, end=",")

[1 2 3 4 5] [6 7 8 9 0] 
1,2,3,4,5,6,7,8,9,0,

In [8]:
# scalar, series, framework
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
# nditer- n dimensional iterator
for x in np.nditer(arr):
    print(x, end=", ")
#for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
#    print(x)


1, 2, 3, 4, 5, 6, 7, 8, 

In [10]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
    print(x)

1
3
5
7


<b>Enumerated Iteration Using ndenumerate()</>

In [11]:
# Enumerated Iteration Using ndenumerate()
# Enumeration means mentioning sequence number of somethings one by one.
for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [23]:
# Joining NumPy Arrays
# We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis.
# If axis is not explicitly passed, it is taken as 0.
b1 = np.array([1,2,3])
b2 = np.array([4,5,6])
c = np.concatenate((b1,b2),0)
print(c)
ab1 = np.array([[1,2,3],[4,5,6]])
ab2 = np.array([[11,22,33],[44,55,66]])
ac = np.concatenate((ab1,ab2),1)
print(ac)
print(ac+2)

[1 2 3 4 5 6]
[[ 1  2  3 11 22 33]
 [ 4  5  6 44 55 66]]
[[ 3  4  5 13 24 35]
 [ 6  7  8 46 57 68]]


<b>Joining arrays using stack functions</b>

In [26]:
#We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=1)
print(arr)
print(np.stack((arr1,arr2)))
#explore hstack method yourself.

[[1 4]
 [2 5]
 [3 6]]
[[1 2 3]
 [4 5 6]]


In [30]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
#convertin 1D array to 3D
print(a.reshape(2,3,2))

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [41]:
print(np.all(a>10), a.var())
print(np.sum(a))

False 11.916666666666666
78


In [43]:
print(arr, np.sum(arr,1))
#np.sum(arr, axis=0,1)

[[1 4]
 [2 5]
 [3 6]] [5 7 9]


In [46]:
rand = np.arange(1,20000,2)
print(rand.size)
%timeit np.sum(rand)
%timeit sum(rand)

10000
10.6 µs ± 737 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
781 µs ± 59.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [63]:
#np.sum is faster than sum funtion given by python
print(a)
print((a>2) & (a<10))
# count the elements which satisfies the condition
np.sum((a>6)&(a<10))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[False False  True  True  True  True  True  True  True False False False]


3