In [2]:
l = [1,2,3,'A','B',4]

In [21]:
#pip install pandas,numpy
import numpy as np
import pandas as pd

In [49]:
a = np.zeros((4,2), dtype='int')
print(a)
print(type(a), a.dtype)
print(a[0], type(a[0]))
#print(help(np.zeros))

[[0 0]
 [0 0]
 [0 0]
 [0 0]]
<class 'numpy.ndarray'> int32
[0 0] <class 'numpy.ndarray'>


In [33]:
arr = np.array([1,2,3,4,5])
z_arr = np.array(50)
twod_arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(type(arr), arr.dtype)
print(z_arr.dtype)
print(twod_arr, twod_arr.dtype)

<class 'numpy.ndarray'> int32
int32
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] int32


In [36]:
int_list = [10,20,30,40,50,5.5]
ilistarr = np.array(int_list)
print(ilistarr, ilistarr.dtype)

str_list = ['A',1,4.5,'B']
str_arr = np.array(str_list)
print(str_arr, str_arr.dtype)

[10.  20.  30.  40.  50.   5.5] float64
['A' '1' '4.5' 'B'] <U32


In [37]:
ll = str_arr.tolist()
print(ll)

['A', '1', '4.5', 'B']


In [50]:
print('string array dimension ',str_arr.ndim, ', Size of array', str_arr.size, str_arr)
print('two dimension array ', twod_arr.ndim, ', Size of array', twod_arr.size, twod_arr)
print(str_arr.shape)
print(twod_arr.shape)
print(np.ones(4))

string array dimension  1 , Size of array 4 ['A' '1' '4.5' 'B']
two dimension array  2 , Size of array 10 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(4,)
(2, 5)
[1. 1. 1. 1.]


In [59]:
emptyarr = np.empty(7)
print(type(emptyarr))
print('np range', np.arange(1,10))
a1 = np.arange(5,50,5)
print(a1)

<class 'numpy.ndarray'>
np range [1 2 3 4 5 6 7 8 9]
[ 5 10 15 20 25 30 35 40 45]


<b> 2D array, accessing the element & getting type of element

In [69]:
l1 = [1,2,3.0]
l2 = [4,5,6]
l3 = [7,8,9]
twod_arr = np.array([l1,l2,l3], dtype='int')
print(twod_arr,twod_arr[2,2], type(twod_arr[0,0]))
print()

[[1 2 3]
 [4 5 6]
 [7 8 9]] 9 <class 'numpy.int32'>



In [84]:
l1 = [1,2,3,4,5]
a1 = np.array(l1)
l2 = [[1,2,3],[4,5,6]]
a2 = np.array(l2)
print(a1[2:], a1[:2], a1[:])
# start:end:step
print(a1[0::2])
print(a1[1::3])

[3 4 5] [1 2] [1 2 3 4 5]
[1 3 5]
[2 5]


In [88]:
#Negative slicing
a1[-4:-1]

array([2, 3, 4])

<b> Slicing two dimensional array</b>

In [93]:
# slicing 2d array
# print(a2[2::2])
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print('Size of Array', arr.size, 'Shape of array', arr.shape)
print(arr[1, 1:4])
# all rows and 3 columns
print(arr[: , :3])

Size of Array 10 Shape of array (2, 5)
[7 8 9]
[[1 2 3]
 [6 7 8]]


In [101]:
# try 3 d array
three_arr = [[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]]
print(np.array(three_arr))
print(three_arr[2][1][0])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
16


In [113]:
print(twod_arr>4)
print(twod_arr)
two_d_arr = twod_arr-3
two_d_arr[2,0]=300
print(twod_arr)
print(two_d_arr)

[[False False False]
 [False  True  True]
 [ True  True  True]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ -2  -1   0]
 [  1   2   3]
 [300   5   6]]


In [124]:
print(a1)
x = a1.copy()
y = a1.view()
# Every NumPy array has the attribute base that returns None if the array owns the data.
# Otherwise, the base  attribute refers to the original object.
print(x.base)
print(y.base)

#ndim refers to n dimensions
tarr = np.array([1,2,3,4,5], ndmin=3)
print(tarr,type(tarr), tarr[0][0][0].dtype)
print(tarr.shape)

[1 2 3 4 5]
None
[1 2 3 4 5]
[[[1 2 3 4 5]]] <class 'numpy.ndarray'> int32
(1, 1, 5)


In [140]:
s1 = [1,2,3,4,5,6,7,8,9,0,11,12]
sarr = np.array(s1)
print(sarr)
re_sarr = sarr.reshape(3,4)
ree = sarr.reshape(2,3,2)
print(sarr)
print(re_sarr)
print(ree)

[ 1  2  3  4  5  6  7  8  9  0 11 12]
[ 1  2  3  4  5  6  7  8  9  0 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9  0 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9  0]
  [11 12]]]


<b>  You are allowed to have one "unknown" dimension.
Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.
Pass -1 as the value, and NumPy will calculate this number for you.</b>

In [143]:
"""You are allowed to have one "unknown" dimension.
Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.
Pass -1 as the value, and NumPy will calculate this number for you.
"""
print(sarr.reshape(2,2,-1))

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [ 0 11 12]]]


In [145]:
#Flattening an array means converting multi dimensional array to 1D array
x = sarr.reshape(2,2,-1)
print(x)
print(x.reshape(-1))

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [ 0 11 12]]]
[ 1  2  3  4  5  6  7  8  9  0 11 12]
