<b>Linear algebra using NumPy</b>

In [1]:
"""Fruit Seller sold 20 mangos and 10 oranges on Friday for a total of Rs.350/-.
He sold 17 mangoes and 27 oranges for Rs 500/- on Saturday. Price of fruit didn't change both days.
What's the price of 1 mango and 1 orange.
"""
"""Two equations will be formed
    20x + 10y = 350
    17x + 27y = 500
"""
import numpy as np
a1 = np.array([20,10])
a2 = np.array([17,27])
b = np.array([350,500])
#Pass LHS and RHS to the solve function
x = np.linalg.solve((a1,a2),b)
print(x)


[12.02702703 10.94594595]


In [2]:
e = np.eye(5, dtype='int')
print(e)
a = np.array([1,2,3,5,4])
print(a.conjugate())

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
[1 2 3 5 4]


In [12]:
# eq1 -> 2x + 3y = 5
# eq2 -> 8x - 4y = 4
lhs = np.array([[2,3], [8,-4]])
rhs = np.array([5,4])
solution = np.linalg.solve(lhs,rhs)
#help(np.linalg.solve)
print(solution)
#help(np.split)

[1. 1.]


In [27]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18])
split_arrays = np.split(arr,3)
print(split_arrays)
#Splitting 2D arrays
arr2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
result = np.split(arr2d,2, axis=1)
print(result)

[array([1, 2, 3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12]), array([13, 14, 15, 16, 17, 18])]
[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12]])]


In [34]:
# searching an ndarray array, will return the indexes where value is 2
x = np.where(arr ==10)

print(arr)

print(x)
print(arr%2==0)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
(array([9], dtype=int64),)
[False  True False  True False  True False  True False  True False  True
 False  True False  True False  True]
